DROP TABLE IF EXISTS gallery CASCADE;
DROP TABLE IF EXISTS devotionals CASCADE;
DROP TABLE IF EXISTS user_roles CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS members CASCADE;
DROP FUNCTION IF EXISTS is_admin_or_staff CASCADE;
DROP FUNCTION IF EXISTS has_role CASCADE;
